// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJlNU1upHAIhTACyj538F1rXXDz9yNw7U',
    appId: '1:242254480071:web:c2daff0558702f834174e2',
    messagingSenderId: '242254480071',
    projectId: 'zego-80174',
    authDomain: 'zego-80174.firebaseapp.com',
    storageBucket: 'zego-80174.firebasestorage.app',
    measurementId: 'G-EESFRCPV4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECpWvBFMHd5sYiwh_viaBm1YKH8cwMWI',
    appId: '1:242254480071:android:b602dd818df434ea4174e2',
    messagingSenderId: '242254480071',
    projectId: 'zego-80174',
    storageBucket: 'zego-80174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn5d9xXQ7YBFLiDPs0b8pBmffzHWp3Duk',
    appId: '1:242254480071:ios:349107e6e1092c974174e2',
    messagingSenderId: '242254480071',
    projectId: 'zego-80174',
    storageBucket: 'zego-80174.firebasestorage.app',
    iosBundleId: 'com.example.zegoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn5d9xXQ7YBFLiDPs0b8pBmffzHWp3Duk',
    appId: '1:242254480071:ios:349107e6e1092c974174e2',
    messagingSenderId: '242254480071',
    projectId: 'zego-80174',
    storageBucket: 'zego-80174.firebasestorage.app',
    iosBundleId: 'com.example.zegoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJlNU1upHAIhTACyj538F1rXXDz9yNw7U',
    appId: '1:242254480071:web:8afcfc7c42f218414174e2',
    messagingSenderId: '242254480071',
    projectId: 'zego-80174',
    authDomain: 'zego-80174.firebaseapp.com',
    storageBucket: 'zego-80174.firebasestorage.app',
    measurementId: 'G-Y95NFJG9CT',
  );
}
